// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAdlaLIvYTP1gry2yxWRVvOImRBc3EB7U',
    appId: '1:421450998662:web:f1ee960dc887f9a504c207',
    messagingSenderId: '421450998662',
    projectId: 'workoutapp-44f23',
    authDomain: 'workoutapp-44f23.firebaseapp.com',
    storageBucket: 'workoutapp-44f23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_OkS610KwIUXNKBbifzG9zDbIFOQeSpM',
    appId: '1:421450998662:android:bc024b810571642104c207',
    messagingSenderId: '421450998662',
    projectId: 'workoutapp-44f23',
    storageBucket: 'workoutapp-44f23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDraX564kR8n8SufBQ0QzLyyeG69ZTqRlc',
    appId: '1:421450998662:ios:56a6c67a8ef7aece04c207',
    messagingSenderId: '421450998662',
    projectId: 'workoutapp-44f23',
    storageBucket: 'workoutapp-44f23.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDraX564kR8n8SufBQ0QzLyyeG69ZTqRlc',
    appId: '1:421450998662:ios:56a6c67a8ef7aece04c207',
    messagingSenderId: '421450998662',
    projectId: 'workoutapp-44f23',
    storageBucket: 'workoutapp-44f23.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAdlaLIvYTP1gry2yxWRVvOImRBc3EB7U',
    appId: '1:421450998662:web:3f0c00699fb5ac3e04c207',
    messagingSenderId: '421450998662',
    projectId: 'workoutapp-44f23',
    authDomain: 'workoutapp-44f23.firebaseapp.com',
    storageBucket: 'workoutapp-44f23.firebasestorage.app',
  );
}
